name: islami_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  shared_preferences: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/files/1.txt
    - assets/files/10.txt
    - assets/files/100.txt
    - assets/files/101.txt
    - assets/files/102.txt
    - assets/files/103.txt
    - assets/files/104.txt
    - assets/files/105.txt
    - assets/files/106.txt
    - assets/files/107.txt
    - assets/files/108.txt
    - assets/files/109.txt
    - assets/files/11.txt
    - assets/files/110.txt
    - assets/files/111.txt
    - assets/files/112.txt
    - assets/files/113.txt
    - assets/files/114.txt
    - assets/files/12.txt
    - assets/files/13.txt
    - assets/files/14.txt
    - assets/files/15.txt
    - assets/files/16.txt
    - assets/files/17.txt
    - assets/files/18.txt
    - assets/files/19.txt
    - assets/files/2.txt
    - assets/files/20.txt
    - assets/files/21.txt
    - assets/files/22.txt
    - assets/files/23.txt
    - assets/files/24.txt
    - assets/files/25.txt
    - assets/files/26.txt
    - assets/files/27.txt
    - assets/files/28.txt
    - assets/files/29.txt
    - assets/files/3.txt
    - assets/files/30.txt
    - assets/files/31.txt
    - assets/files/32.txt
    - assets/files/33.txt
    - assets/files/34.txt
    - assets/files/35.txt
    - assets/files/36.txt
    - assets/files/37.txt
    - assets/files/38.txt
    - assets/files/39.txt
    - assets/files/4.txt
    - assets/files/40.txt
    - assets/files/41.txt
    - assets/files/42.txt
    - assets/files/43.txt
    - assets/files/44.txt
    - assets/files/45.txt
    - assets/files/46.txt
    - assets/files/47.txt
    - assets/files/48.txt
    - assets/files/49.txt
    - assets/files/5.txt
    - assets/files/50.txt
    - assets/files/51.txt
    - assets/files/52.txt
    - assets/files/53.txt
    - assets/files/54.txt
    - assets/files/55.txt
    - assets/files/56.txt
    - assets/files/57.txt
    - assets/files/58.txt
    - assets/files/59.txt
    - assets/files/6.txt
    - assets/files/60.txt
    - assets/files/61.txt
    - assets/files/62.txt
    - assets/files/63.txt
    - assets/files/64.txt
    - assets/files/65.txt
    - assets/files/66.txt
    - assets/files/67.txt
    - assets/files/68.txt
    - assets/files/69.txt
    - assets/files/7.txt
    - assets/files/70.txt
    - assets/files/71.txt
    - assets/files/72.txt
    - assets/files/73.txt
    - assets/files/74.txt
    - assets/files/75.txt
    - assets/files/76.txt
    - assets/files/77.txt
    - assets/files/78.txt
    - assets/files/79.txt
    - assets/files/8.txt
    - assets/files/80.txt
    - assets/files/81.txt
    - assets/files/82.txt
    - assets/files/83.txt
    - assets/files/84.txt
    - assets/files/85.txt
    - assets/files/86.txt
    - assets/files/87.txt
    - assets/files/88.txt
    - assets/files/89.txt
    - assets/files/9.txt
    - assets/files/90.txt
    - assets/files/91.txt
    - assets/files/92.txt
    - assets/files/93.txt
    - assets/files/94.txt
    - assets/files/95.txt
    - assets/files/96.txt
    - assets/files/97.txt
    - assets/files/98.txt
    - assets/files/99.txt
    - assets/files/ahadeth.txt
    - assets/icons/hadithIcon.png
    - assets/icons/num_border.png
    - assets/icons/quranIcon.png
    - assets/icons/radioIcon.png
    - assets/icons/sebhaIcon.png
    - assets/icons/timesIcon.png
    - assets/images/HadithCardBk.png
    - assets/images/QuranDtBottom.png
    - assets/images/QuranDtLeft.png
    - assets/images/QuranDtRght.png
    - assets/images/SebhaBody.png
    - assets/images/hadith_bk.png
    - assets/images/most_recent_bk.png
    - assets/images/oBc2.png
    - assets/images/oBc3.png
    - assets/images/oBc4.png
    - assets/images/oBc5.png
    - assets/images/onBoardingCenter.png
    - assets/images/onBoardingTop.png
    - assets/images/quran_bk.png
    - assets/images/radio_bk.png
    - assets/images/sebhaTop.png
    - assets/images/sebha_bk.png
    - assets/images/splash/GlowTop.png
    - assets/images/splash/Islami.png
    - assets/images/splash/LeftShape.png
    - assets/images/splash/MosqueTop.png
    - assets/images/splash/icon.png
    - assets/images/splash/rightShape.png
    - assets/images/splash/routegold.png
    - assets/images/splash/splashBk.png
    - assets/images/sura_dt_bk.png
    - assets/images/times_bk.png
  fonts:
    - family: Janna-LT-Bold
      fonts:
        - asset: assets/fonts/Janna-LT-Bold.ttf
