// /// Generated file. Do not edit.
// /// This file is generated by the iFlutter
//
// // ignore_for_file: constant_identifier_names
// // ignore_for_file: lines_longer_than_80_chars
// class AssetsRes {
//   AssetsRes._();
//
//   static const String PLUGIN_NAME = 'islami_app';
//   static const String PLUGIN_VERSION = '1.0.0+1';
//   static const String
//
//   1
//
//   =
//
//   '
//
//   assets/files/1.txt
//
//   ';
//
//   static const String
//
//   10
//
//   =
//
//   '
//
//   assets/files/10.txt
//
//   ';
//
//   static const String
//
//   100
//
//   =
//
//   '
//
//   assets/files/100.txt
//
//   ';
//
//   static const String
//
//   101
//
//   =
//
//   '
//
//   assets/files/101.txt
//
//   ';
//
//   static const String
//
//   102
//
//   =
//
//   '
//
//   assets/files/102.txt
//
//   ';
//
//   static const String
//
//   103
//
//   =
//
//   '
//
//   assets/files/103.txt
//
//   ';
//
//   static const String
//
//   104
//
//   =
//
//   '
//
//   assets/files/104.txt
//
//   ';
//
//   static const String
//
//   105
//
//   =
//
//   '
//
//   assets/files/105.txt
//
//   ';
//
//   static const String
//
//   106
//
//   =
//
//   '
//
//   assets/files/106.txt
//
//   ';
//
//   static const String
//
//   107
//
//   =
//
//   '
//
//   assets/files/107.txt
//
//   ';
//
//   static const String
//
//   108
//
//   =
//
//   '
//
//   assets/files/108.txt
//
//   ';
//
//   static const String
//
//   109
//
//   =
//
//   '
//
//   assets/files/109.txt
//
//   ';
//
//   static const String
//
//   11
//
//   =
//
//   '
//
//   assets/files/11.txt
//
//   ';
//
//   static const String
//
//   110
//
//   =
//
//   '
//
//   assets/files/110.txt
//
//   ';
//
//   static const String
//
//   111
//
//   =
//
//   '
//
//   assets/files/111.txt
//
//   ';
//
//   static const String
//
//   112
//
//   =
//
//   '
//
//   assets/files/112.txt
//
//   ';
//
//   static const String
//
//   113
//
//   =
//
//   '
//
//   assets/files/113.txt
//
//   ';
//
//   static const String
//
//   114
//
//   =
//
//   '
//
//   assets/files/114.txt
//
//   ';
//
//   static const String
//
//   12
//
//   =
//
//   '
//
//   assets/files/12.txt
//
//   ';
//
//   static const String
//
//   13
//
//   =
//
//   '
//
//   assets/files/13.txt
//
//   ';
//
//   static const String
//
//   14
//
//   =
//
//   '
//
//   assets/files/14.txt
//
//   ';
//
//   static const String
//
//   15
//
//   =
//
//   '
//
//   assets/files/15.txt
//
//   ';
//
//   static const String
//
//   16
//
//   =
//
//   '
//
//   assets/files/16.txt
//
//   ';
//
//   static const String
//
//   17
//
//   =
//
//   '
//
//   assets/files/17.txt
//
//   ';
//
//   static const String
//
//   18
//
//   =
//
//   '
//
//   assets/files/18.txt
//
//   ';
//
//   static const String
//
//   19
//
//   =
//
//   '
//
//   assets/files/19.txt
//
//   ';
//
//   static const String
//
//   2
//
//   =
//
//   '
//
//   assets/files/2.txt
//
//   ';
//
//   static const String
//
//   20
//
//   =
//
//   '
//
//   assets/files/20.txt
//
//   ';
//
//   static const String
//
//   21
//
//   =
//
//   '
//
//   assets/files/21.txt
//
//   ';
//
//   static const String
//
//   22
//
//   =
//
//   '
//
//   assets/files/22.txt
//
//   ';
//
//   static const String
//
//   23
//
//   =
//
//   '
//
//   assets/files/23.txt
//
//   ';
//
//   static const String
//
//   24
//
//   =
//
//   '
//
//   assets/files/24.txt
//
//   ';
//
//   static const String
//
//   25
//
//   =
//
//   '
//
//   assets/files/25.txt
//
//   ';
//
//   static const String
//
//   26
//
//   =
//
//   '
//
//   assets/files/26.txt
//
//   ';
//
//   static const String
//
//   27
//
//   =
//
//   '
//
//   assets/files/27.txt
//
//   ';
//
//   static const String
//
//   28
//
//   =
//
//   '
//
//   assets/files/28.txt
//
//   ';
//
//   static const String
//
//   29
//
//   =
//
//   '
//
//   assets/files/29.txt
//
//   ';
//
//   static const String
//
//   3
//
//   =
//
//   '
//
//   assets/files/3.txt
//
//   ';
//
//   static const String
//
//   30
//
//   =
//
//   '
//
//   assets/files/30.txt
//
//   ';
//
//   static const String
//
//   31
//
//   =
//
//   '
//
//   assets/files/31.txt
//
//   ';
//
//   static const String
//
//   32
//
//   =
//
//   '
//
//   assets/files/32.txt
//
//   ';
//
//   static const String
//
//   33
//
//   =
//
//   '
//
//   assets/files/33.txt
//
//   ';
//
//   static const String
//
//   34
//
//   =
//
//   '
//
//   assets/files/34.txt
//
//   ';
//
//   static const String
//
//   35
//
//   =
//
//   '
//
//   assets/files/35.txt
//
//   ';
//
//   static const String
//
//   36
//
//   =
//
//   '
//
//   assets/files/36.txt
//
//   ';
//
//   static const String
//
//   37
//
//   =
//
//   '
//
//   assets/files/37.txt
//
//   ';
//
//   static const String
//
//   38
//
//   =
//
//   '
//
//   assets/files/38.txt
//
//   ';
//
//   static const String
//
//   39
//
//   =
//
//   '
//
//   assets/files/39.txt
//
//   ';
//
//   static const String
//
//   4
//
//   =
//
//   '
//
//   assets/files/4.txt
//
//   ';
//
//   static const String
//
//   40
//
//   =
//
//   '
//
//   assets/files/40.txt
//
//   ';
//
//   static const String
//
//   41
//
//   =
//
//   '
//
//   assets/files/41.txt
//
//   ';
//
//   static const String
//
//   42
//
//   =
//
//   '
//
//   assets/files/42.txt
//
//   ';
//
//   static const String
//
//   43
//
//   =
//
//   '
//
//   assets/files/43.txt
//
//   ';
//
//   static const String
//
//   44
//
//   =
//
//   '
//
//   assets/files/44.txt
//
//   ';
//
//   static const String
//
//   45
//
//   =
//
//   '
//
//   assets/files/45.txt
//
//   ';
//
//   static const String
//
//   46
//
//   =
//
//   '
//
//   assets/files/46.txt
//
//   ';
//
//   static const String
//
//   47
//
//   =
//
//   '
//
//   assets/files/47.txt
//
//   ';
//
//   static const String
//
//   48
//
//   =
//
//   '
//
//   assets/files/48.txt
//
//   ';
//
//   static const String
//
//   49
//
//   =
//
//   '
//
//   assets/files/49.txt
//
//   ';
//
//   static const String
//
//   5
//
//   =
//
//   '
//
//   assets/files/5.txt
//
//   ';
//
//   static const String
//
//   50
//
//   =
//
//   '
//
//   assets/files/50.txt
//
//   ';
//
//   static const String
//
//   51
//
//   =
//
//   '
//
//   assets/files/51.txt
//
//   ';
//
//   static const String
//
//   52
//
//   =
//
//   '
//
//   assets/files/52.txt
//
//   ';
//
//   static const String
//
//   53
//
//   =
//
//   '
//
//   assets/files/53.txt
//
//   ';
//
//   static const String
//
//   54
//
//   =
//
//   '
//
//   assets/files/54.txt
//
//   ';
//
//   static const String
//
//   55
//
//   =
//
//   '
//
//   assets/files/55.txt
//
//   ';
//
//   static const String
//
//   56
//
//   =
//
//   '
//
//   assets/files/56.txt
//
//   ';
//
//   static const String
//
//   57
//
//   =
//
//   '
//
//   assets/files/57.txt
//
//   ';
//
//   static const String
//
//   58
//
//   =
//
//   '
//
//   assets/files/58.txt
//
//   ';
//
//   static const String
//
//   59
//
//   =
//
//   '
//
//   assets/files/59.txt
//
//   ';
//
//   static const String
//
//   6
//
//   =
//
//   '
//
//   assets/files/6.txt
//
//   ';
//
//   static const String
//
//   60
//
//   =
//
//   '
//
//   assets/files/60.txt
//
//   ';
//
//   static const String
//
//   61
//
//   =
//
//   '
//
//   assets/files/61.txt
//
//   ';
//
//   static const String
//
//   62
//
//   =
//
//   '
//
//   assets/files/62.txt
//
//   ';
//
//   static const String
//
//   63
//
//   =
//
//   '
//
//   assets/files/63.txt
//
//   ';
//
//   static const String
//
//   64
//
//   =
//
//   '
//
//   assets/files/64.txt
//
//   ';
//
//   static const String
//
//   65
//
//   =
//
//   '
//
//   assets/files/65.txt
//
//   ';
//
//   static const String
//
//   66
//
//   =
//
//   '
//
//   assets/files/66.txt
//
//   ';
//
//   static const String
//
//   67
//
//   =
//
//   '
//
//   assets/files/67.txt
//
//   ';
//
//   static const String
//
//   68
//
//   =
//
//   '
//
//   assets/files/68.txt
//
//   ';
//
//   static const String
//
//   69
//
//   =
//
//   '
//
//   assets/files/69.txt
//
//   ';
//
//   static const String
//
//   7
//
//   =
//
//   '
//
//   assets/files/7.txt
//
//   ';
//
//   static const String
//
//   70
//
//   =
//
//   '
//
//   assets/files/70.txt
//
//   ';
//
//   static const String
//
//   71
//
//   =
//
//   '
//
//   assets/files/71.txt
//
//   ';
//
//   static const String
//
//   72
//
//   =
//
//   '
//
//   assets/files/72.txt
//
//   ';
//
//   static const String
//
//   73
//
//   =
//
//   '
//
//   assets/files/73.txt
//
//   ';
//
//   static const String
//
//   74
//
//   =
//
//   '
//
//   assets/files/74.txt
//
//   ';
//
//   static const String
//
//   75
//
//   =
//
//   '
//
//   assets/files/75.txt
//
//   ';
//
//   static const String
//
//   76
//
//   =
//
//   '
//
//   assets/files/76.txt
//
//   ';
//
//   static const String
//
//   77
//
//   =
//
//   '
//
//   assets/files/77.txt
//
//   ';
//
//   static const String
//
//   78
//
//   =
//
//   '
//
//   assets/files/78.txt
//
//   ';
//
//   static const String
//
//   79
//
//   =
//
//   '
//
//   assets/files/79.txt
//
//   ';
//
//   static const String
//
//   8
//
//   =
//
//   '
//
//   assets/files/8.txt
//
//   ';
//
//   static const String
//
//   80
//
//   =
//
//   '
//
//   assets/files/80.txt
//
//   ';
//
//   static const String
//
//   81
//
//   =
//
//   '
//
//   assets/files/81.txt
//
//   ';
//
//   static const String
//
//   82
//
//   =
//
//   '
//
//   assets/files/82.txt
//
//   ';
//
//   static const String
//
//   83
//
//   =
//
//   '
//
//   assets/files/83.txt
//
//   ';
//
//   static const String
//
//   84
//
//   =
//
//   '
//
//   assets/files/84.txt
//
//   ';
//
//   static const String
//
//   85
//
//   =
//
//   '
//
//   assets/files/85.txt
//
//   ';
//
//   static const String
//
//   86
//
//   =
//
//   '
//
//   assets/files/86.txt
//
//   ';
//
//   static const String
//
//   87
//
//   =
//
//   '
//
//   assets/files/87.txt
//
//   ';
//
//   static const String
//
//   88
//
//   =
//
//   '
//
//   assets/files/88.txt
//
//   ';
//
//   static const String
//
//   89
//
//   =
//
//   '
//
//   assets/files/89.txt
//
//   ';
//
//   static const String
//
//   9
//
//   =
//
//   '
//
//   assets/files/9.txt
//
//   ';
//
//   static const String
//
//   90
//
//   =
//
//   '
//
//   assets/files/90.txt
//
//   ';
//
//   static const String
//
//   91
//
//   =
//
//   '
//
//   assets/files/91.txt
//
//   ';
//
//   static const String
//
//   92
//
//   =
//
//   '
//
//   assets/files/92.txt
//
//   ';
//
//   static const String
//
//   93
//
//   =
//
//   '
//
//   assets/files/93.txt
//
//   ';
//
//   static const String
//
//   94
//
//   =
//
//   '
//
//   assets/files/94.txt
//
//   ';
//
//   static const String
//
//   95
//
//   =
//
//   '
//
//   assets/files/95.txt
//
//   ';
//
//   static const String
//
//   96
//
//   =
//
//   '
//
//   assets/files/96.txt
//
//   ';
//
//   static const String
//
//   97
//
//   =
//
//   '
//
//   assets/files/97.txt
//
//   ';
//
//   static const String
//
//   98
//
//   =
//
//   '
//
//   assets/files/98.txt
//
//   ';
//
//   static const String
//
//   99
//
//   =
//
//   '
//
//   assets/files/99.txt
//
//   ';
//
//   static const String AHADETH = 'assets/files/ahadeth.txt';
//   static const String HADITHICON = 'assets/icons/hadithIcon.png';
//   static const String NUM_BORDER = 'assets/icons/num_border.png';
//   static const String QURANICON = 'assets/icons/quranIcon.png';
//   static const String RADIOICON = 'assets/icons/radioIcon.png';
//   static const String SEBHAICON = 'assets/icons/sebhaIcon.png';
//   static const String TIMESICON = 'assets/icons/timesIcon.png';
//   static const String HADITHCARDBK = 'assets/images/HadithCardBk.png';
//   static const String QURANDTBOTTOM = 'assets/images/QuranDtBottom.png';
//   static const String QURANDTLEFT = 'assets/images/QuranDtLeft.png';
//   static const String QURANDTRGHT = 'assets/images/QuranDtRght.png';
//   static const String SEBHABODY = 'assets/images/SebhaBody.png';
//   static const String EVENING_AZKAR = 'assets/images/evening_azkar.png';
//   static const String HADITH_BK = 'assets/images/hadith_bk.png';
//   static const String MORNING_AZKAR = 'assets/images/morning_azkar.png';
//   static const String MOST_RECENT_BK = 'assets/images/most_recent_bk.png';
//   static const String OBC2 = 'assets/images/oBc2.png';
//   static const String OBC3 = 'assets/images/oBc3.png';
//   static const String OBC4 = 'assets/images/oBc4.png';
//   static const String OBC5 = 'assets/images/oBc5.png';
//   static const String ONBOARDINGCENTER = 'assets/images/onBoardingCenter.png';
//   static const String ONBOARDINGTOP = 'assets/images/onBoardingTop.png';
//   static const String QURAN_BK = 'assets/images/quran_bk.png';
//   static const String RADIOBG = 'assets/images/radioBG.png';
//   static const String RADIO_BK = 'assets/images/radio_bk.png';
//   static const String SALLAH_TIME = 'assets/images/sallah_time.png';
//   static const String SEBHATOP = 'assets/images/sebhaTop.png';
//   static const String SEBHA_BK = 'assets/images/sebha_bk.png';
//   static const String SOUNDON = 'assets/images/soundOn.png';
//   static const String GLOWTOP = 'assets/images/splash/GlowTop.png';
//   static const String ISLAMI = 'assets/images/splash/Islami.png';
//   static const String LEFTSHAPE = 'assets/images/splash/LeftShape.png';
//   static const String MOSQUETOP = 'assets/images/splash/MosqueTop.png';
//   static const String ICON = 'assets/images/splash/icon.png';
//   static const String RIGHTSHAPE = 'assets/images/splash/rightShape.png';
//   static const String ROUTEGOLD = 'assets/images/splash/routegold.png';
//   static const String SPLASHBK = 'assets/images/splash/splashBk.png';
//   static const String SURA_DT_BK = 'assets/images/sura_dt_bk.png';
//   static const String TIME_BG = 'assets/images/time_bg.png';
//   static const String TIMES_BK = 'assets/images/times_bk.png';
// }
